services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      - ENV=development
    volumes:
      - ./:/app/
      - ./resources/frankenphp/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8080:80
