services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      - ENV=development
    volumes:
      - ./:/app/:rw
      - ./resources/frankenphp/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 8080:80

volumes:
  caddy_data:
  caddy_config:
