name: Run Tests

on:
  push:
    branches:
      - '**'  # runs on every branch push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Run tests
        run: make test
